spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${BANGLOG_DB_URL}
    username: ${BANGLOG_DB_USERNAME}
    password: ${BANGLOG_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

banglog:
  ops:
    environment-name: prod

logging:
  level:
    root: INFO
    com.banglog: INFO
