spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${BANGPOT_DB_URL:${DB_URL:}}
    username: ${BANGPOT_DB_USERNAME:${DB_USERNAME:}}
    password: ${BANGPOT_DB_PASSWORD:${DB_PASSWORD:}}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

bangpot:
  ops:
    environment-name: prod

logging:
  level:
    root: INFO
    com.bangpot: INFO
